apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-calendrer-ay-uploads
  namespace: calendar-ay
  labels:
    app: calendrer-ay
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-static
