apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-calendrer-ay-logs
  namespace: calendar-ay
  labels:
    app: calendrer-ay
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-static
