apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-calendar-ay-logs
  labels:
    app: calendrer-ay
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.20
    path: /srv/nfs/calendar-ay/logs
