apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-wp-content
 namespace: wordpress
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 8Gi
 storageClassName: nfs-static
