apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      app.kubernetes.io/name: wordpress
      app.kubernetes.io/instance: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        app.kubernetes.io/name: wordpress
        app.kubernetes.io/instance: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.5-apache
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wordpress-config
            - secretRef:
                name: wordpress-secret
          startupProbe:
            httpGet:
              path: /wp-admin/install.php
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /wp-admin/install.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /wp-admin/install.php
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: wp-content
              mountPath: /var/www/html/wp-content
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: pvc-wp-content
