{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wp-content
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "wordpress.labels" . | indent 4 }}
spec:
  accessModes:
{{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
