apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "wordpress.labels" . | indent 4 }}
type: Opaque
stringData:
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.dbPassword | quote }}
